# Generated by Django 5.1.1 on 2024-10-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_remove_game_players_gamescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='template_name',
            field=models.CharField(default='games/game_detail.html', max_length=100),
        ),
    ]
